source "http://rubygems.org"

gem "sinatra", "~> 1.2.3"
gem "shotgun", "~> 0.9"
gem "haml", "~> 3.1.1"
gem "sass", "~> 3.1.1"
gem "datamapper", "~> 1.2.0"
gem "dm-sqlite-adapter", "~> 1.2.0"
gem "grid-coordinates", "~> 1.1.4"
gem "mail", "~> 2.4.1"
gem "stripe", "~> 1.5.17"